### ISSUE TITLE
Once started the vpn client the server lost the ssh connection

### ISSUE THREAD

**Issue by jogulpdata** [alexjesustech/globalprotect-app-for-linux#1]
Once started the vpn client the server lost the ssh connection

**Comment by alexjesustech** [comment]
There are some things you can try if the server loses SSH connection after starting the VPN client.

Check your VPN client settings. Make sure the VPN client is configured to use the same IP address and port as the SSH server. You can also try changing the VPN protocol to see if that resolves the issue.
Check your SSH server settings. Ensure that the SSH server is configured to allow connections from VPN clients. You can also try changing the SSH port to see if that resolves the problem.
Check your internet connection. Make sure you have an internet connection, and the speed is fast enough to support the SSH connection.
Disable any firewalls or antivirus software that may be blocking the SSH connection.
Restart your VPN client, SSH server, and router. This may help fix any temporary issues that could be causing the problem.
If you are still having trouble connecting to the SSH server after trying these steps, contact your VPN client support or SSH server provider for further assistance.
